# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(276, 357)
        calculator.setAutoFillBackground(True)
        self.button1 = QtWidgets.QPushButton(calculator)
        self.button1.setGeometry(QtCore.QRect(30, 90, 51, 41))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(calculator)
        self.button2.setGeometry(QtCore.QRect(80, 90, 51, 41))
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(calculator)
        self.button3.setGeometry(QtCore.QRect(130, 90, 51, 41))
        self.button3.setObjectName("button3")
        self.button4 = QtWidgets.QPushButton(calculator)
        self.button4.setGeometry(QtCore.QRect(30, 130, 51, 41))
        self.button4.setObjectName("button4")
        self.button5 = QtWidgets.QPushButton(calculator)
        self.button5.setGeometry(QtCore.QRect(80, 130, 51, 41))
        self.button5.setObjectName("button5")
        self.button6 = QtWidgets.QPushButton(calculator)
        self.button6.setGeometry(QtCore.QRect(130, 130, 51, 41))
        self.button6.setObjectName("button6")
        self.button7 = QtWidgets.QPushButton(calculator)
        self.button7.setGeometry(QtCore.QRect(30, 170, 51, 41))
        self.button7.setObjectName("button7")
        self.button8 = QtWidgets.QPushButton(calculator)
        self.button8.setGeometry(QtCore.QRect(80, 170, 51, 41))
        self.button8.setObjectName("button8")
        self.button9 = QtWidgets.QPushButton(calculator)
        self.button9.setGeometry(QtCore.QRect(130, 170, 51, 41))
        self.button9.setObjectName("button9")
        self.button0 = QtWidgets.QPushButton(calculator)
        self.button0.setGeometry(QtCore.QRect(80, 210, 51, 41))
        self.button0.setObjectName("button0")
        self.buttonDot = QtWidgets.QPushButton(calculator)
        self.buttonDot.setGeometry(QtCore.QRect(30, 210, 51, 41))
        self.buttonDot.setObjectName("buttonDot")
        self.buttonDel = QtWidgets.QPushButton(calculator)
        self.buttonDel.setGeometry(QtCore.QRect(130, 210, 51, 41))
        self.buttonDel.setObjectName("buttonDel")
        self.buttonPlus = QtWidgets.QPushButton(calculator)
        self.buttonPlus.setGeometry(QtCore.QRect(180, 90, 51, 41))
        self.buttonPlus.setObjectName("buttonPlus")
        self.buttonSub = QtWidgets.QPushButton(calculator)
        self.buttonSub.setGeometry(QtCore.QRect(180, 130, 51, 41))
        self.buttonSub.setObjectName("buttonSub")
        self.buttonMult = QtWidgets.QPushButton(calculator)
        self.buttonMult.setGeometry(QtCore.QRect(180, 170, 51, 41))
        self.buttonMult.setObjectName("buttonMult")
        self.buttonDevide = QtWidgets.QPushButton(calculator)
        self.buttonDevide.setGeometry(QtCore.QRect(180, 210, 51, 41))
        self.buttonDevide.setObjectName("buttonDevide")
        self.buttonLparent = QtWidgets.QPushButton(calculator)
        self.buttonLparent.setGeometry(QtCore.QRect(30, 250, 51, 41))
        self.buttonLparent.setObjectName("buttonLparent")
        self.buttonRparent = QtWidgets.QPushButton(calculator)
        self.buttonRparent.setGeometry(QtCore.QRect(80, 250, 51, 41))
        self.buttonRparent.setObjectName("buttonRparent")
        self.buttonCE = QtWidgets.QPushButton(calculator)
        self.buttonCE.setGeometry(QtCore.QRect(130, 250, 51, 41))
        self.buttonCE.setObjectName("buttonCE")
        self.buttonEnter = QtWidgets.QPushButton(calculator)
        self.buttonEnter.setGeometry(QtCore.QRect(180, 250, 51, 41))
        self.buttonEnter.setObjectName("buttonEnter")
        self.textEdit = QtWidgets.QTextEdit(calculator)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(30, 60, 201, 31))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(calculator)
        self.button1.clicked.connect(calculator.pressButton1)
        self.button2.clicked.connect(calculator.pressButton2)
        self.button3.clicked.connect(calculator.pressButton3)
        self.button4.clicked.connect(calculator.pressButton4)
        self.button5.clicked.connect(calculator.pressButton5)
        self.button6.clicked.connect(calculator.pressButton6)
        self.button7.clicked.connect(calculator.pressButton7)
        self.button8.clicked.connect(calculator.pressButton8)
        self.button9.clicked.connect(calculator.pressButton9)
        self.button0.clicked.connect(calculator.pressButton0)
        self.buttonDot.clicked.connect(calculator.pressButtonDot)
        self.buttonLparent.clicked.connect(calculator.pressButtonLparent)
        self.buttonRparent.clicked.connect(calculator.pressButtonRparent)
        self.buttonDel.clicked.connect(calculator.pressButtonDel)
        self.buttonCE.clicked.connect(calculator.pressButtonCE)
        self.buttonEnter.clicked.connect(calculator.pressButtonEnter)
        self.buttonDevide.clicked.connect(calculator.pressButtonDevide)
        self.buttonMult.clicked.connect(calculator.pressButtonMult)
        self.buttonSub.clicked.connect(calculator.pressButtonSub)
        self.buttonPlus.clicked.connect(calculator.pressButtonPlus)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "Form"))
        self.button1.setText(_translate("calculator", "1"))
        self.button2.setText(_translate("calculator", "2"))
        self.button3.setText(_translate("calculator", "3"))
        self.button4.setText(_translate("calculator", "4"))
        self.button5.setText(_translate("calculator", "5"))
        self.button6.setText(_translate("calculator", "6"))
        self.button7.setText(_translate("calculator", "7"))
        self.button8.setText(_translate("calculator", "8"))
        self.button9.setText(_translate("calculator", "9"))
        self.button0.setText(_translate("calculator", "0"))
        self.buttonDot.setText(_translate("calculator", "."))
        self.buttonDel.setText(_translate("calculator", "del"))
        self.buttonPlus.setText(_translate("calculator", "+"))
        self.buttonSub.setText(_translate("calculator", "-"))
        self.buttonMult.setText(_translate("calculator", "*"))
        self.buttonDevide.setText(_translate("calculator", "/"))
        self.buttonLparent.setText(_translate("calculator", "("))
        self.buttonRparent.setText(_translate("calculator", ")"))
        self.buttonCE.setText(_translate("calculator", "CE"))
        self.buttonEnter.setText(_translate("calculator", "enter"))

